


""" brain.py """

utils = {'generate_substrate': 0,
         'activation_function': 0}

substrate = {'init': 0,
             'step': 0,
             'update': 0,
             'check_dna': 0,
             'initialize': 0,
             'collect_input': 0,
             'add_loss': 0,
             'get_loss': 0,
             'get_output': 0,
             'get_trainable_params': 0,
             'get_trainable_names': 0,
             'get_nb_trainable': 0,
             'is_trainable': 0,
             'get_nb_output': 0,
             'get_substrate_name': 0,
             'get_dna': 0,
             'update_dna': 0,
             'is_initialize': 0,
             'reset': 0}

substrateStructure = {'init': 0,
                      'step': 0,
                      'update': 0,
                      'collect_input': 0,
                      'check_dna': 0,
                      'build_structure': 0,
                      'get_output': 0,
                      'get_activity': 0,
                      'get_trainable_params': 0,
                      'get_trainable_names': 0,
                      'is_trainable': 0,
                      'get_nb_trainable': 0,
                      'get_nb_output': 0,
                      'get_connections': 0,
                      'get_nb_inout': 0,
                      'set_livestream': 0,
                      'add_grapher': 0,
                      'show_graph': 0,
                      'get_grapher': 0,
                      'reset': 0}

protein = {'init': [['Utils', 'activation_function'],
                    ['Protein', 'check_dna']],
           'step': 0,
           'update': 0,
           'check_dna': 0,
           'initialize': [['Protein', 'update_dna']],
           'collect_input': 0,
           'add_loss': 0,
           'get_loss': 0,
           'get_output': 0,
           'get_trainable_params': 0,
           'get_trainable_names': 0,
           'get_nb_trainable': 0,
           'get_nb_output': 0,
           'get_substrate_name': 0,
           'get_dna': 0,
           'is_initialize': 0,
           'is_trainable': 0,
           'update_dna': 0,
           'reset': 0}


cell = {'init': [['Cell', 'check_dna'],
                 ['SubstrateStructure', 'build_structure']],
        'check_dna': 0,
        'step': [['Protein', 'get_output'],
                 ['Protein', 'collect_input'],
                 ['Protein', 'step'],
                 ['Protein', 'get_output']],
        'update': [['Protein', 'add_loss'],
                   ['Protein', 'get_loss'],
                   ['Protein', 'update']],
        'build_structure': [['Utils', 'generate_substrate'],
                            ['Protein', 'init'],
                            ['Protein', 'initialize'],
                            ['Protein', 'get_nb_trainable'],
                            ['Protein', 'get_trainable_names']],
        'collect_input': 0,
        'add_loss': 0,
        'get_loss': 0,
        'get_output': 0,
        'get_activity': 0,
        'get_trainable_params': [['Protein', 'get_trainable_params']],
        'get_trainable_names': 0,
        'get_nb_trainable': 0,
        'get_nb_output': 0,
        'get_connections': 0,
        'get_nb_inout': 0,
        'get_substrate_name': 0,
        'get_dna': 0,
        'is_trainable': 0,
        'is_initialize': 0,
        'get_grapher': [['Grapher', 'init']],
        'set_livestream': [['Grapher', 'initialize']],
        'show_graph': [['Grapher', 'draw_graph']],
        'update_dna': 0,
        'reset': 0
        }


cellPlasticity = {'init': [['Cell', 'check_dna'],
                           ['SubstrateStructure', 'build_structure']],
                  'check_dna': 0,
                  'step': [['Substrate', 'get_output'],
                           ['Protein', 'collect_input'],
                           ['Protein', 'step'],
                           ['Substrate', 'get_output']],
                  'update': [['Protein', 'add_loss'],
                             ['Substrate', 'get_loss'],
                             ['Protein', 'update'],
                             ['Cell', 'collect_internals']],
                  'build_structure': [['Utils', 'generate_substrate'],
                                      ['Protein', 'init'],
                                      ['Protein', 'initialize'],
                                      ['Protein', 'get_nb_trainable'],
                                      ['Protein', 'get_trainable_names']],
                  'collect_internals': 0,
                  'collect_input': 0,
                  'add_loss': 0,
                  'get_loss': 0,
                  'get_output': 0,
                  'get_activity': 0,
                  'get_trainable_params': [['Protein', 'get_trainable_params']],
                  'get_trainable_names': 0,
                  'get_nb_trainable': 0,
                  'get_nb_output': 0,
                  'get_connections': 0,
                  'get_nb_inout': 0,
                  'get_grapher': [['Grpher', 'init']],
                  'is_trainable': 0,
                  'is_initialize': 0,
                  'set_livestream': [['Grapher', 'initialize']], 
                  'show_graph': [['Grapher', 'draw_graph']],
                  'update_dna': 0,
                  'reset': 0
                  }


""" Protein instances """

proteinExp = {'init': [['Utils', 'activation_function']],
              'step': 0,
              'update': 0,
              'add_loss': 0,
              'check_dna': 0,
              'get_trainable_params': 0,
              'initialize': [['ProteinExp', 'update_dna']],
              'update_dna': 0,
              'reset': 0}


proteinBase = {'init': [['Utils', 'activation_function']],
               'step': 0,
               'update': 0,
               'add_loss': 0,
               'get_trainable_params': 0,
               'initialize': [['ProteinBase', 'update_dna']],
               'update_dna': 0}


proteinCond = {'init': [['Utils', 'activation_function']],
               'step': 0,
               'update': 0,
               'add_loss': 0,
               'get_trainable_params': 0,
               'initialize': [['ProteinCond', 'update_dna']],
               'update_dna': 0}



""" sim.py """

testmap = {'init': 0,
           'add_input': 0,
           'add_target': 0,
           'rigenerate_data': [['TestMap', 'add_input'],
                               ['TestMap', 'add_target']],
           'plot_stimuli': [['TestMap', 'plot_raster']],
           'plot_raster': 0,
           'testing': [['AgentEvo', 'collect_input'],
                       ['AgentEvo', 'step'],
                       ['AgentEvo', 'get_output'],
                       ['AgentEvo', 'set_fitness']],
           'is_complete': 0,
           }

gym = {'init': 0,
       'add_substrate': ['Substrate', 'initialize'],
       'simulation': [['Substrate', 'is_trainable'],
                      ['Substrate', 'get_nb_output'],
                      ['Substrate', 'get_nb_output'],
                      ['Substrate', 'collect_input'],
                      ['Substrate', 'step'],
                      ['Substrate', 'get_output'],
                      ['Substrate', 'add_loss'],
                      ['Substrate', 'update'],
                      ['TestMap', 'plot_raster']],
       'long_simulation': [['Substrate', 'is_trainable'],
                           ['Substrate', 'get_nb_output'],
                           ['Substrate', 'get_nb_trainable'],
                           ['Substrate', 'get_trainable_names'],
                           ['TestMap', 'rigenerate_data'],
                           ['Substrate', 'collect_input'],
                           ['Substrate', 'step'],
                           ['Substrate', 'get_output'],
                           ['Substrate', 'add_loss'],
                           ['Substrate', 'update'],
                           ['Substrate', 'get_trainable_params'],
                           ['TestMap', 'plot_raster']],
       'test_substrate': [['AgentEvo', 'init'],
                          ['TestMap', 'testing']],
       'plot_classes_test': [['Substrate', 'collect_input'],
                             ['Substrate', 'step'],
                             ['Substrate', 'get_output']],
       'get_input': 0,
       'get_target': 0}

agentevo = {'init': 0,
            'step': [['Substrate', 'step'],
                     ['Substrate', 'get_output']],
            'collect_input': [['Substrate', 'collect_input']],
            'get_output': 0,
            'get_fitness': 0,
            'get_dna': [['Substrate', 'get_dna']],
            'get_substrate': 0,
            'get_info': 0,
            'get_name': 0,
            'set_fitness': 0,
            'reset': [['Substrate', 'reset']]}

dna_generator = {'init': 0,
                 'sample_protein': 0,
                 'new_dna': 0,
                 'generate': [['DnaGenerator', 'new_dna'],
                              ['DnaGenerator', 'mutate'],
                              ['DnaGenerator', 'cross'],
                              ['Utils', 'generate_substrate']],
                 'mutate': [['DnaGenerator', 'mutate_protein']],
                 'mutate_protein': [['DnaGenerator', 'mutation_prob'],
                                    ['DnaGenerator', 'mutation_rate']],
                 'cross': [['DnaGenerator', 'new_dna']],
                 'mutation_prob': 0,
                 'mutation_rate': 0,
                 'get_dna': 0}

simple_evolution = {'init': [['TestMap', 'is_complete']],
                    'evolve': [['SimpleEvolution', 'new_generation'],
                               ['SimpleEvolution', 'fit'],
                               ['SimpleEvolution', 'record']],
                    'new_generation': [['DnaGenerator', 'generate'],
                                       ['SimpleEvolution', 'inherit_name'],
                                       ['AgentEvo', 'init'],
                                       ['AgentEvo', 'reset'],
                                       ['AgentEvo', 'get_substrate'],
                                       ['AgentEvo', 'get_name']],
                    'fit': [['SimpleEvolution', 'shell']],
                    'shell': [['TestMap', 'testing']],
                    'record': [['AgentEvo', 'get_fitness']],
                    'get_fitted_dna': [['AgentEvo', 'get_info']],
                    'random_name': 0,
                    'inherit_name': 0,
                    'show_fittest': [['TestMap', 'testing']]}


""" tools.py """

grapher = {'init': [['Grapher', 'build']],
           'initialize': 0,
           'live_graph': 0,
           'draw_graph': 0,
           'build': 0,
           'set_pause': 0}



########################################################

classes_dict = {'Substrate': substrate,
                'SubstrateStructure': substrateStructure,
                'Protein': protein,
                'Cell': cell,
                'CellPlasticity': cellPlasticity,
                'TestMap': testmap,
                'Gym': gym,
                'AgentEvo': agentevo,
                'SimpleEvolution': simple_evolution,
                'DnaGenerator': dna_generator,
                'Grapher': grapher,
                'Utils': utils}

